// src/utils/countryCodes.ts
export const countryCodes = [
  { code: "+1", label: "USA / Canada" },
  { code: "+44", label: "United Kingdom" },
  { code: "+91", label: "India" },
  { code: "+61", label: "Australia" },
  { code: "+81", label: "Japan" },
  { code: "+49", label: "Germany" },
  { code: "+33", label: "France" },
  { code: "+39", label: "Italy" },
  { code: "+86", label: "China" },
  { code: "+7", label: "Russia" },
  { code: "+34", label: "Spain" },
  { code: "+55", label: "Brazil" },
  { code: "+27", label: "South Africa" },
  { code: "+62", label: "Indonesia" },
  { code: "+82", label: "South Korea" },
  { code: "+90", label: "Turkey" },
  { code: "+351", label: "Portugal" },
  { code: "+971", label: "United Arab Emirates" },
  { code: "+964", label: "Iraq" },
  { code: "+92", label: "Pakistan" },
  { code: "+880", label: "Bangladesh" },
  { code: "+94", label: "Sri Lanka" },
  { code: "+60", label: "Malaysia" },
  { code: "+65", label: "Singapore" },
  { code: "+66", label: "Thailand" },
  { code: "+63", label: "Philippines" },
  { code: "+20", label: "Egypt" },
  { code: "+972", label: "Israel" },
  { code: "+968", label: "Oman" },
  { code: "+974", label: "Qatar" },
  { code: "+973", label: "Bahrain" },
  { code: "+965", label: "Kuwait" },
  { code: "+966", label: "Saudi Arabia" },
  { code: "+212", label: "Morocco" },
  { code: "+254", label: "Kenya" },
  { code: "+256", label: "Uganda" },
  { code: "+255", label: "Tanzania" },
  { code: "+251", label: "Ethiopia" },
  { code: "+598", label: "Uruguay" },
  { code: "+58", label: "Venezuela" },
  { code: "+57", label: "Colombia" },
  { code: "+593", label: "Ecuador" },
  { code: "+591", label: "Bolivia" },
  { code: "+54", label: "Argentina" },
  { code: "+64", label: "New Zealand" },
  { code: "+852", label: "Hong Kong" },
  { code: "+853", label: "Macau" },
  { code: "+886", label: "Taiwan" },
  { code: "+998", label: "Uzbekistan" },
  { code: "+380", label: "Ukraine" },
  { code: "+48", label: "Poland" },
  { code: "+36", label: "Hungary" },
  { code: "+30", label: "Greece" },
  { code: "+40", label: "Romania" },
  { code: "+421", label: "Slovakia" },
  { code: "+420", label: "Czech Republic" },
  { code: "+46", label: "Sweden" },
  { code: "+358", label: "Finland" },
  { code: "+47", label: "Norway" },
  { code: "+45", label: "Denmark" },
  { code: "+41", label: "Switzerland" },
  { code: "+31", label: "Netherlands" },
  { code: "+32", label: "Belgium" },
  { code: "+43", label: "Austria" },
  { code: "+376", label: "Andorra" },
  { code: "+352", label: "Luxembourg" },
  { code: "+377", label: "Monaco" },
  { code: "+380", label: "Ukraine" },
  { code: "+994", label: "Azerbaijan" },
  { code: "+995", label: "Georgia" },
  { code: "+373", label: "Moldova" },
  { code: "+374", label: "Armenia" },
  { code: "+381", label: "Serbia" },
  { code: "+382", label: "Montenegro" },
  { code: "+383", label: "Kosovo" },
  { code: "+389", label: "North Macedonia" },
  { code: "+359", label: "Bulgaria" },
  { code: "+386", label: "Slovenia" },
  { code: "+385", label: "Croatia" },
  // ✅ Add rest of countries here or fetch dynamically from an API
];
